package com.example.nempille.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

//this annotation tells Room that this class
//represents table in the database
@Entity(tableName = "medications")

data class MedicationEntity (
    @PrimaryKey(autoGenerate = true)
    //PK autogenerated id for each row
    val id: Long = 0L,
    //id of the patient (user) to whom medication belongs
    val userId: Long,
    //name - ibuprofen
    val name: String,
    val dosage: String,
    //how many times a day
    val frequencyPerDay: Int,
    //optional notes
    val notes: String? = null
)

//why entity? 1. room stores kotlin objects inside SQLite database
//each entity - one table
//each property - one column